# Generated by Django 3.2.11 on 2022-01-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=100)),
                ('vieicle', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('license', models.CharField(max_length=10)),
            ],
        ),
    ]
